# Generated by Django 6.0.2 on 2026-03-01 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0002_blogdetailtags_blogdetail_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetail',
            name='body',
        ),
    ]
