# Generated by Django 6.0.2 on 2026-03-05 06:50

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0005_alter_blogdetail_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='body',
            field=wagtail.fields.StreamField([('info', 0), ('faq', 1), ('text', 2), ('image', 3), ('carousel', 7)], blank=True, block_lookup={0: ('blocks.blocks.InfoBlock', (), {}), 1: ('blocks.blocks.FAQListBlock', (), {}), 2: ('blocks.blocks.TextBlock', (), {}), 3: ('blocks.blocks.ImageBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.TextBlock', (), {}), 6: ('wagtail.blocks.StructBlock', [[('text', 5), ('author', 5)]], {}), 7: ('wagtail.blocks.StreamBlock', [[('image', 4), ('quotation', 6)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='blogdetailtags',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
