# Generated by Django 6.0.2 on 2026-03-16 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0008_author_expire_at_author_expired_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetail',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blogpages.author'),
        ),
    ]
