# Generated by Django 6.0.2 on 2026-03-17 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0010_author_locked_author_locked_at_author_locked_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': [('can_edit_author_name', 'Can edit author name')]},
        ),
    ]
