# Generated by Django 6.0.2 on 2026-05-10 13:44

from django.db import migrations
from wagtail.models import BootstrapTranslatableModel


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0012_author_locale_author_translation_key'),
    ]

    operations = [
        BootstrapTranslatableModel('blogpages.Author'),
    ]
