# Generated by Django 6.0.2 on 2026-05-10 17:59

from django.db import migrations
from wagtail.models import BootstrapTranslatableModel


def ensure_author_translation_columns(apps, schema_editor):
    """Repair DB drift where migration state has fields but SQLite table does not."""
    table_name = "blogpages_author"

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"PRAGMA table_info({table_name})")
        existing_columns = {row[1] for row in cursor.fetchall()}

    if "locale_id" not in existing_columns:
        schema_editor.execute(
            "ALTER TABLE blogpages_author "
            "ADD COLUMN locale_id INTEGER "
            "REFERENCES wagtailcore_locale(id) "
            "DEFERRABLE INITIALLY DEFERRED"
        )

    if "translation_key" not in existing_columns:
        schema_editor.execute(
            "ALTER TABLE blogpages_author "
            "ADD COLUMN translation_key char(32)"
        )


def ensure_author_translation_unique_index(apps, schema_editor):
    schema_editor.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS "
        "blogpages_author_translation_key_locale_id_uniq "
        "ON blogpages_author (translation_key, locale_id)"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0014_alter_author_locale_alter_author_translation_key_and_more'),
    ]

    operations = [
        migrations.RunPython(
            ensure_author_translation_columns,
            migrations.RunPython.noop,
        ),
        BootstrapTranslatableModel('blogpages.Author'),
        migrations.RunPython(
            ensure_author_translation_unique_index,
            migrations.RunPython.noop,
        ),
    ]
