# Generated by Django 6.0.2 on 2026-02-21 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('home', '0006_homepage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='custom_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.customdocument'),
        ),
    ]
