# Generated by Django 6.0.2 on 2026-02-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepage_cta_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='cta_external_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
